// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: mq.proto

package mq

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// MQService defines service.
type MQService interface {
	TestMQAdd(ctx context.Context, req *TestMQAddRequest) (*TestMQAddResponse, error) // @alias=/demo/mq/add
}

func MQService_TestMQAdd_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &TestMQAddRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(MQService).TestMQAdd(ctx, reqbody.(*TestMQAddRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// MQServer_ServiceDesc descriptor for server.RegisterService.
var MQServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.demo.mq.MQ",
	HandlerType: ((*MQService)(nil)),
	Methods: []server.Method{
		{
			Name: "/demo/mq/add",
			Func: MQService_TestMQAdd_Handler,
		},
		{
			Name: "/trpc.demo.mq.MQ/TestMQAdd",
			Func: MQService_TestMQAdd_Handler,
		},
	},
}

// RegisterMQService registers service.
func RegisterMQService(s server.Service, svr MQService) {
	if err := s.Register(&MQServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("MQ register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedMQ struct{}

func (s *UnimplementedMQ) TestMQAdd(ctx context.Context, req *TestMQAddRequest) (*TestMQAddResponse, error) {
	return nil, errors.New("rpc TestMQAdd of service MQ is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// MQClientProxy defines service client proxy
type MQClientProxy interface {
	TestMQAdd(ctx context.Context, req *TestMQAddRequest, opts ...client.Option) (rsp *TestMQAddResponse, err error) // @alias=/demo/mq/add
}

type MQClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewMQClientProxy = func(opts ...client.Option) MQClientProxy {
	return &MQClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *MQClientProxyImpl) TestMQAdd(ctx context.Context, req *TestMQAddRequest, opts ...client.Option) (*TestMQAddResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/demo/mq/add")
	msg.WithCalleeServiceName(MQServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("demo")
	msg.WithCalleeServer("mq")
	msg.WithCalleeService("MQ")
	msg.WithCalleeMethod("TestMQAdd")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &TestMQAddResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
