
linters-settings:
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
    packages-with-error-messages:
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
  gocritic:
    enabled-tags:
    disabled-checks:
  funlen:
    lines: 100
    statements: 80

linters:
  # inverted configuration with enable-all and disable is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    # - deadcode # The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    # - golint #  linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner. Replaced by revive.
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    # - interfacer # The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.
    - lll
    - misspell
    # - nakedret
    # - scopelint # The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner. Replaced by exportloopref.
    - staticcheck
    # - structcheck # The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck # The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused.
    - whitespace

  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals

run:

issues:
  exclude-dirs:
    - testdata
    - bin
  issues-exit-code: 1

output:
  print-issued-lines: false
service:
  golangci-lint-version: 1.19.x 


