// Code generated by 'go generate'. DO NOT EDIT.

package errs

import "trpc.group/trpc-go/trpc-go/errs"

const (
	// ParameterWrongCode 错误代码: 请求参数错误
	ParameterWrongCode = 10000
	// PasswordErrorCode 错误代码: 密码比对失败
	PasswordErrorCode = 10011
)

var (
	// ParameterWrong 请求参数错误
	ParameterWrong = errs.New(ParameterWrongCode, "请求参数错误")
	// PasswordError 密码比对失败
	PasswordError = errs.New(PasswordErrorCode, "密码比对失败")
)
