#!/bin/bash

# 请将需要配置的错误码按顺序定义在这个数组中
# 分别是: 错误码, 常量名, 错误说明, 额外注释 (可选)
_err_desc=(
    # 系统通用错误
    '10000 | ParameterWrong | 请求参数错误'
    # 登陆错误
    '10011 | PasswordError | 密码错误 | 密码比对失败'
)

_curr_to_file="error_codes.go"
function toFile() {
    echo -e $1 >> ${_curr_to_file}
}

# reference: [shell字符串去掉首尾空格](https://juejin.cn/s/shell字符串去掉首尾空格)
ret=""
function strip() {
    ret=$1
    ret="$(echo -e "${ret}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
}

rm -f "error_codes.go"

toFile "// Code generated by 'go generate'. DO NOT EDIT."
toFile ""
toFile "package errs"
toFile ""
toFile "import \"trpc.group/trpc-go/trpc-go/errs\""
toFile ""

# 常量定义
# reference: [【shell】shell字符串分割|文件分割](https://blog.51cto.com/liangchaoxi/4159669)

# 首先解析出参数
_err_codes=()
_err_consts=()
_err_comments=()

_old_ifs="${IFS}"
IFS="|"
for i in "${!_err_desc[@]}"; do
    item=${_err_desc[${i}]}
    arr=(${item})
    
    strip ${arr[0]}; code=${ret}
    strip ${arr[1]}; const=${ret}
    strip ${arr[2]}; comment=${ret}

    if [ ! -z "${arr[3]}" ]; then
        strip ${arr[3]}; comment=${ret}
    fi

    _err_codes[${i}]=${code}
    _err_consts[${i}]=${const}
    _err_comments[${i}]=${comment}
done
IFS="${_old_ifs}"

# 首先定义 code
toFile "const ("
for i in "${!_err_codes[@]}"; do
    code=${_err_codes[${i}]}
    const=${_err_consts[${i}]}
    comment=${_err_comments[${i}]}

    toFile "\t// ${const}Code 错误代码: ${comment}"
    toFile "\t${const}Code = ${code}"
done
toFile ")"

# 然后定义 error
toFile "var ("
for i in "${!_err_codes[@]}"; do
    const=${_err_consts[${i}]}
    comment=${_err_comments[${i}]}

    toFile "\t// ${const} ${comment}"
    toFile "\t${const} = errs.New(${const}Code, \"${comment}\")"
done
toFile ")"

go fmt error_codes.go

