// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/Andrew-M-C/go.util/runtime/caller"
	"github.com/Andrew-M-C/trpc-go-demo/app/user/repo"
	"github.com/Andrew-M-C/trpc-go-demo/app/user/repo/account"
	"github.com/Andrew-M-C/trpc-go-demo/app/user/service"
	"github.com/Andrew-M-C/trpc-go-demo/proto/user"
	"github.com/Andrew-M-C/trpc-go-demo/utils/filter/count"
	"github.com/Andrew-M-C/trpc-go-demo/utils/filter/elapse"
	"github.com/Andrew-M-C/trpc-go-utils/client/sqlx"
	"github.com/Andrew-M-C/trpc-go-utils/codec"
	"github.com/Andrew-M-C/trpc-go-utils/config/etcd"
	"github.com/Andrew-M-C/trpc-go-utils/errs"
	"github.com/Andrew-M-C/trpc-go-utils/log"
	log2 "github.com/Andrew-M-C/trpc-go-utils/metrics/log"
	"github.com/Andrew-M-C/trpc-go-utils/recovery"
	"github.com/google/wire"
	"trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/server"
)

import (
	_ "trpc.group/trpc-go/trpc-naming-polarismesh"
	_ "trpc.group/trpc-go/trpc-naming-polarismesh/selector"
)

// Injectors from wire.go:

func newApplication() (application, error) {
	server, err := provideTRPCService()
	if err != nil {
		return nil, err
	}
	accountRepo, err := provideAccountRepo()
	if err != nil {
		return nil, err
	}
	mainApplication, err := provideUserService(server, accountRepo)
	if err != nil {
		return nil, err
	}
	return mainApplication, nil
}

// wire.go:

var trpcSet = wire.NewSet(
	provideTRPCService,
)

func provideTRPCService() (s *server.Server, err error) {
	defer recovery.CatchPanic(recovery.WithCallback(func(_ context.Context, info any, stack []caller.Caller) {
		err = fmt.Errorf("panic info '%v', stack '%v'", info, log.ToJSON(stack))
	}),
	)
	errs.SetDigestDescription("错误码")
	errs.RegisterErrToCodeFilter()
	log.RegisterTraceLogFilter()
	log2.RegisterMetricsMySQL()
	elapse.RegisterFilter()
	count.RegisterFilter()
	codec.UseOfficialJSON()

	s = trpc.NewServer()

	// trpc 初始化后置
	const clientYAMLKey = "/demo/general/client.yaml"
	if err := etcd.RegisterClientProvider(context.Background(), s, clientYAMLKey); err != nil {
		return nil, err
	}

	return s, nil
}

var repoSet = wire.NewSet(
	provideAccountRepo,
)

func provideAccountRepo() (repo.AccountRepo, error) {
	d := account.Dependency{
		DBGetter: sqlx.ClientGetter("mysql.demo.user.account"),
	}
	return account.New(d)
}

var serviceSet = wire.NewSet(
	provideUserService,
)

func provideUserService(
	svr *server.Server,
	accountRepo repo.AccountRepo,
) (application, error) {
	d := service.Dependency{
		AccountRepo: accountRepo,
	}
	userSvc, err := service.New(d)
	if err != nil {
		return nil, err
	}
	user.RegisterUserService(svr, userSvc)
	return svr, nil
}
